exports['GoYoshi buildReleasePullRequest combines google-api-go-client autogenerated PR 1'] = `
:robot: I have created a release *beep* *boop*
---


## 0.1.0 (1983-10-10)


### Features

* **all:** auto-regenerate discovery clients, refs [#1281](https://github.com/googleapis/google-api-go-client/issues/1281) [#1280](https://github.com/googleapis/google-api-go-client/issues/1280) [#1279](https://github.com/googleapis/google-api-go-client/issues/1279) [#1278](https://github.com/googleapis/google-api-go-client/issues/1278)

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).
`

exports['GoYoshi buildReleasePullRequest filters out submodule commits 1'] = `
:robot: I have created a release *beep* *boop*
---


## 0.1.0 (1983-10-10)


### Features

* some generic feature ([5c5e4ab](https://github.com/googleapis/go-yoshi-test-repo/commit/5c5e4ab88ed278b50d0fd0208d142639))


### Bug Fixes

* some generic fix ([a151e7a](https://github.com/googleapis/go-yoshi-test-repo/commit/a151e7a6d7914c7c5e59c077362816be))
* **translate:** some translate fix ([a74c6a3](https://github.com/googleapis/go-yoshi-test-repo/commit/a74c6a3c43273a62de7e47bef2e11fb0))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).
`
