exports['GoYoshi buildReleasePullRequest combines google-api-go-client autogenerated PR 1'] = `
:robot: I have created a release *beep* *boop*
---


## 0.1.0 (1983-10-10)


### Features

* **all:** auto-regenerate discovery clients, refs [#1281](https://github.com/googleapis/google-api-go-client/issues/1281) [#1280](https://github.com/googleapis/google-api-go-client/issues/1280) [#1279](https://github.com/googleapis/google-api-go-client/issues/1279) [#1278](https://github.com/googleapis/google-api-go-client/issues/1278)

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).
`

exports['GoYoshi buildReleasePullRequest filters out submodule commits 1'] = `
:robot: I have created a release *beep* *boop*
---


## 0.1.0 (1983-10-10)


### Bug Fixes

* **translate:** some translate fix ([a74c6a3](https://github.com/googleapis/google-cloud-go/commit/a74c6a3c43273a62de7e47bef2e11fb0))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).
`

exports['GoYoshi buildReleasePullRequest filters out touched files not matching submodule commits 1'] = `
:robot: I have created a release *beep* *boop*
---


## 0.1.0 (1983-10-10)


### Bug Fixes

* **iam/apiv1:** some firestore fix ([6daedf3](https://github.com/googleapis/google-cloud-go/commit/6daedf3971d9e1b4c99ff1b3a52c94a5))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).
`
