name: Build from sources and create release PRs

on:
  push:
    branches:
      - main

jobs:
  build-and-open-releas-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable && corepack prepare
      # Note: actions/setup-node doesn't yet provide parameters for corepack, we need to run it again after enabling it
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Create release PRs
        run: |
          pnpm start release-pr \
                  --token=${{ secrets.GITHUB_TOKEN }} \
                  --repo-url=${{ github.repository }} \
                  --target-branch=main
