name: Build from sources and create release PRs

on:
  push:
    branches:
      - main

jobs:
  build-and-open-releas-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Compile
        run: npm run compile

      - name: Create release PRs
        run: |
          npm run cli -- release-pr \
                      --token=${{ secrets.GITHUB_TOKEN }} \
                      --repo-url=${{ github.repository }} \
                      --target-branch=main
