name: Create GitHub releases

on:
  push:
    branches:
      - release

jobs:
  create-releases:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Create release
        run: |
          npm run cli -- github-release \
                      --token=${{ secrets.GITHUB_TOKEN }} \
                      --repo-url=${{ github.repository }} \
                      --target-branch=release
